### ISSUE TITLE
Unnecessary margin shift at 1440px in measure tool

### ISSUE THREAD

**Issue by alexandersandberg** [GoogleChrome/web.dev#1181]
**Describe the bug**
There's an unnecessary margin shift at 1440px and above, according to the CSS below. See GIF 1 for a demonstration.

```css
@media screen and (min-width: 1440px) {
    ...
    web-lighthouse-scores .lh-report-meta {
        margin-bottom: 32px;
    }
    ...
}
```

**To Reproduce**
Visist [/measure](https://web.dev/measure) and resize browser past/below 1440px width.

**Expected behavior**
Margins between elements are more consistent and visually pleasing _with_ the `margin-bottom: 32px`, so I think it would be better to add the bottom margin earlier, at the 840px breakpoint. There's no reason to only add it at 1440px and above since it works and looks great at 840px and above.

See GIF 2 below for a prototyped demonstration of this proposal.

**Screenshots**
![Current margin behavior](https://user-images.githubusercontent.com/35671299/61596194-c1a05b00-ac00-11e9-8e59-0a7391ed2dea.gif)
_GIF 1. Current behavior: margin added at 1440px._

![Proposed margin behavior](https://user-images.githubusercontent.com/35671299/61596322-0a0c4880-ac02-11e9-89c5-2f4ce98a0ead.gif)
_GIF 2. Proposed behavior: add margin at 840px (when buttons are no longer stacked)._
