### ISSUE TITLE
Consider making 'Current Status' a reusable component

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1821]
See [this link](https://web.dev/sms-receiver-api-announcement/#current-status) for an example. These are used in all Fugu posts and many other besides. Updating the parameters to the component may not be any quicker than updating raw markdown. However, a reusable component would have the advantage of consistent formatting.

I'm not in love with the idea, but I'll create one if people think I should.

**Comment by robdodson** [comment]
Not opposed to this. During our recent chromestatus meeting with me, you, chris, and jason, there was talk of having chromestatus clearly sign post the history of an API. I was kind of curious if we would ultimately want to widgetize whatever they decide to create there. We could do our own thing initially, but ultimately we'd probably want to align with their presentation and terminology.

**Comment by jpmedley** [comment]
I think doing our own thing initially is the right move. The signposting you're referring to is more complicated than it seems meaning it will take time to design and implement while the number of places it could be used grows.

Moving to a simple widget now will make it easier to convert to something more sophisticated later. It would mean the conversion would start with greping the web.dev source for the simple widget name rather than manually viewing every published article. In other words, this gives us something we can do now that's not hard to change.

**Comment by robdodson** [comment]
yep, the feature sounds fine to me. Did you want to take a shot at working on it?

**Comment by jpmedley** [comment]
I had always intended to.

**Comment by jpmedley** [comment]
Here's the metadata we would need to add to an article if we had a status widget. [Here's an example](https://web.dev/native-file-system/#status) of a hard-coded status table.

```
status:
  explainer: *https://some/url*
  explainer-status: Complete
  spec: *https://some/url*
  spec-status: Complete
  feedback: *https://some/url*
  feedback-status: In progress
  origin-trial-status: In progress
  launch-status: Not started
```
