### ISSUE TITLE
Add `scroll-margin` to headings

### ISSUE THREAD

**Issue by Malvoz** [GoogleChrome/web.dev#1951]
Currently if I visit a section anchor, e.g. https://web.dev/native-lazy-loading/#what-if-i'm-already-using-a-third-party-library-or-a-script-to-lazy-load-images-or-iframes, the `<web-header>` is covering the corresponding heading, forcing me to scroll up to read the heading.

While [`scroll-margin`](https://www.w3.org/TR/css-scroll-snap-1/#scroll-margin) may solve this, it probably doesn't have full browser coverage, in the past I've personally used negative margin-top in concjunction to padding-top to give room for a fixed element.

For reference, https://httpwg.org/faq/spec/ does this:
```CSS
*:not([href])[id]:before {
    display: block;
    content: " ";
    margin-top: -65px;
    height: 65px;
    visibility: hidden;
}
```

An `@supports` rule could be used to fall back to the "hacky" variant of choice. Thanks!
