### ISSUE TITLE
content: css @property

### ISSUE THREAD

**Issue by ramiy** [GoogleChrome/web.dev#4260]
### What page(s) need to be updated?

* https://web.dev/at-property/
* https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/blog/at-property/index.md

### Why is this update needed?

Missing syntax for multiple properties / list of properties.

Is it:

```css
@property --xxx,
@property --yyy {
}
```

or:

```css
@property --xxx, --yyy {
}
```

or something else?

@una

**Comment by una** [comment]
Hi Ramiy. I'm not sure where you would have a usecase in which you would want two identical variables in the same scope. To have two custom properties, it would the applying @property to each, ie.:

```
@property --yyy {
  ... values here ...
}

@property --zzz {
 ... values here ...
}
```

**Comment by ramiy** [comment]
@una example use case:

```css
@property --color-1,
@property --color-2,
@property --color-3,
@property --color-4,
@property --color-5 {
  syntax: '<color>';
  initial-value: transparent;
  inherits: false;
}
```

----

Another example:

```css
@property --color-1,
@property --color-2,
@property --color-3 {
  syntax: '<color>';
  inherits: true;
}

@property --color-1 {
  initial-value: red;
}

@property --color-2 {
  initial-value: green;
}

@property --color-3 {
  initial-value: blue;
}
```

----

Real life example:

I'm the creator of **[Charts.css](https://chartscss.org/)** and the framework has [several variables](https://github.com/ChartsCSS/charts.css/blob/master/src/general/_variables.scss#L31-L39) that have [the same scope](https://chartscss.org/components/axes/). The variables share the same scope but each has a different purpose.

```css
@property --primary-axis-style,
@property --secondary-axes-style,
@property --data-axes-style {
  syntax: '<string>';
  initial-value: solid;
  inherits: true;
}

@property --primary-axis-width,
@property --secondary-axes-width,
@property --data-axes-width {
  syntax: '<length>';
  initial-value: 1px;
  inherits: true;
}
```
