### ISSUE TITLE
✏️ [Learn CSS] Update Spacing CodePen 

### ISSUE THREAD

**Issue by vegerot** [GoogleChrome/web.dev#5706]
### What page(s) need to be updated?

https://web.dev/learn/css/spacing/#padding
https://codepen.io/web-dot-dev/pen/eYgRrzz

### Explanation

I may not be understanding the logic in the example, but I don't understand why the switch is toggling the `width` instead of `box-sizing`, even though the results look similar.  Is it because of the animation?  In this proposal I modify the CSS from instead of changing the `width`, to change the `box-sizing`.  Unfortunately this makes the pretty transition no longer work (is this why you used `width` instead of `box-sizing` in the first place?)

Additionally, you say "`box-sizing` value of `content-box` -- the initial value--".  However, since the example uses `reset.css`, it actually sets the default value to `border-box`.  In this proposal I reset it to `box-sizing: initial`.

For the same reason I propose changing the label to instead say "Turn on `box-sizing: border-box`" and updating the event listener to reflect that.

### Proposed change

Change the CSS in the example to 

```css
.my-element {
  width: 320px;
  padding: 30px;
  background: var(--color-primary-x-light);
  border: 1px solid var(--color-primary);
}

.my-element[data-size='border-box'] {
  box-sizing: border-box
}

.my-element[data-size='content-box'] {
  box-sizing: content-box
}

.my-element > * + * {
  margin-top: 1em;
}

/* Presentation Styling */
* {
  box-sizing: initial;
}
```

### Why is this update needed?

To make the example show what it is meant to describe
