### ISSUE TITLE
Extra colon in the code example of Houdini's properties and values API

### ISSUE THREAD

**Issue by ChloeLiang** [GoogleChrome/web.dev#9885]
**Describe the bug**

Extra colon after `--stop-color` in transition:

```css
button {
  --stop-color: red;
  transition: --stop-color: 1s;
}
```

**To Reproduce**
1. Go to https://web.dev/css-props-and-vals/
2. Scroll down to 'Animating custom properties'
3. See the first code example

**Expected behavior**
`transition: --stop-color 1s;`

**Screenshots**
<img width="331" alt="image" src="https://user-images.githubusercontent.com/28077042/231034450-32aa135f-2151-48da-a9ff-e32924a42002.png">
